apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs-share
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  storageClassName: nfs
  nfs:
    server: 10.3.2.188
    path: /mnt/nfs_share
  persistentVolumeReclaimPolicy: Retain
