apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv-v2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: nfs
  nfs:
    server: 10.3.2.188
    path: /nfs_share/jellyfin/config
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv-v2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  storageClassName: nfs
  nfs:
    server: 10.3.2.188
    path: /nfs_share/jellyfin/data
  persistentVolumeReclaimPolicy: Retain