apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: nfs
  nfs:
    server: 10.3.2.188
    path: /nfs-share/jellyfin/config
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  storageClassName: nfs
  nfs:
    server: 10.3.2.188
    path: /nfs-share/jellyfin/media
  persistentVolumeReclaimPolicy: Retain