apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfs-share
  namespace: jellyfin
spec:
  volumeName: jellyfin-nfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
  