apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nldon/secrets.git
  ref:
    branch: main
  secretRef:
    name: flux-secrets-deploy
