apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional-scrape-configs.yaml: |
    - job_name: 'proxmox-nodes'
      static_configs:
        - targets: ['10.3.2.201:9100', '10.3.2.202:9100']
