apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = http://grafana.donlab.uk
    [auth]
    disable_login_form = true
    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = grafana-oauth
    client_secret = OzyIcwMyLAHrGI0moFwUe40PknCNMFeH
    scopes = openid email profile offline_access roles
    email_attribute_path = email
    login_attribute_path = username
    name_attribute_path = full_name
    auth_url = http://keycloak.donlab.uk/realms/donlab/protocol/openid-connect/auth
    token_url = http://keycloak.donlab.uk/realms/donlab/protocol/openid-connect/token
    user_info_url = http://keycloak.donlab.uk/realms/donlab/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
