apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
data:
  grafana.ini: |
    [auth]
    disable_login_form = true
    [auth.generic_oauth]
    enabled = true
    name = Keycloak
    allow_sign_up = true
    client_id = grafana
    client_secret = 4YdvrM5v0cTz3NOkndI7WW67ei0KLBgC
    scopes = openid,profile,email
    auth_url = https://keycloak.donlab.uk/auth/realms/donlab/protocol/openid-connect/auth
    token_url = https://keycloak.donlab.uk/auth/realms/donlab/protocol/openid-connect/token
    user_info_url = https://keycloak.donlab.uk/auth/realms/donlab/protocol/openid-connect/userinfo
