apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      adminPassword: "admin"
      service:
        type: ClusterIP
      extraConfigMapMounts:
        - name: grafana-custom-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
          configMap:
            name: grafana-custom-config
            namespace: monitoring
    prometheus:
      service:
        type: ClusterIP
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'proxmox-nodes'
            static_configs:
              - targets: ['10.3.2.201:9100', '10.3.2.202:9100']
