apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-keycloak
    namespace: flux-system
  values:
    auth:
      adminUser: admin
      adminPassword: admin
    service:
      type: ClusterIP
    postgresql:
      enabled: true
      auth:
        postgresPassword: admin
        password: admin
