apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-keycloak
    namespace: flux-system
  values:
    auth:
      adminUser: admin
      adminPassword: admin
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: keycloak.donlab.uk
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      tls: false
    postgresql:
      enabled: true
      auth:
        postgresPassword: admin
        password: admin
