apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: gpu-test
spec:
  containers:
    - name: gpu-test
      image: nvidia/cuda:12.0-base
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
  restartPolicy: Never
  nodeSelector:
    nvidia.com/gpu: "true"