apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
  namespace: monitoring
spec:
  interval: 5m
  releaseName: dcgm-exporter
  chart:
    spec:
      chart: dcgm-exporter
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
  values:
    service:
      enabled: true
    podLabels:
      app.kubernetes.io/name: dcgm-exporter
